'use strict';
(() => {
  const $ = id => document.getElementById(id);
  const ns = 'http://www.w3.org/2000/svg';
  const colors = {normal:'#5d9273', inspect:'#cf7250', pending:'#c5a750', withheld:'#b9c1b3'};
  let bundle = window.RAIMAL_DATA, run, records = [];
  try { records = JSON.parse(localStorage.getItem('raimal-checks-v1') || '[]'); if (!Array.isArray(records)) records = []; } catch { records = []; }
  function node(tag, text, className) { const el = document.createElement(tag); if (text !== undefined) el.textContent = text; if (className) el.className = className; return el; }
  function svg(tag, attrs) { const el = document.createElementNS(ns, tag); for (const [k,v] of Object.entries(attrs)) el.setAttribute(k,v); return el; }
  function option(value, text) { const o = node('option',text); o.value=value; return o; }
  function download(obj, filename) { const url=URL.createObjectURL(new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}));const a=node('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000); }
  function validate(b) {
    if (!b || b.schema_version !== 1 || typeof b.synthetic_demo !== 'boolean' || !Array.isArray(b.dates) || !b.dates.length || b.dates.length>250 || !Array.isArray(b.observations) || b.observations.length>12000 || !b.runs) throw Error('Use a bundle generated by the included Python exporter.');
    const datePattern=/^\d{4}-\d{2}-\d{2}$/;
    if (new Set(b.dates).size!==b.dates.length || !b.dates.every(d=>datePattern.test(d)&&Number.isFinite(Date.parse(d)))) throw Error('Invalid observation dates.');
    for (const day of b.dates) for (const pct of [80,90,100]) {
      const r=b.runs[`${day}:${pct}`];
      if (!r || r.analysis_date!==day || r.synthetic_demo!==b.synthetic_demo || !Array.isArray(r.zones) || r.zones.length!==48 || !Array.isArray(r.tasks)) throw Error('Missing or inconsistent dated analysis.');
      const keys = new Set();
      for (const z of r.zones) {
        if (!Number.isInteger(z.sector)||z.sector<0||z.sector>11||!Number.isInteger(z.ring)||z.ring<0||z.ring>3||keys.has(`${z.sector}:${z.ring}`)||!Object.hasOwn(colors,z.status)||!Number.isFinite(z.ndvi)||z.ndvi < -1||z.ndvi>1||!Number.isFinite(z.valid_coverage)||z.valid_coverage<0||z.valid_coverage>1||typeof z.zone_id!=='string'||typeof z.question!=='string') throw Error('Invalid sector values in analysis.');
        if (!b.synthetic_demo && (!z.source_id || !Number.isFinite(z.center_lat)||!Number.isFinite(z.center_lon)||!Number.isFinite(z.radius_m)||z.radius_m<=0)) throw Error('Imported observations require source IDs and field geometry.');
        keys.add(`${z.sector}:${z.ring}`);
      }
    }
    return b;
  }
  function setup() {
    $('date').replaceChildren(...bundle.dates.map(d=>option(d,new Date(d+'T00:00:00Z').toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'}))));
    $('date').value=bundle.dates.at(-1);
    $('dataset-badge').textContent=bundle.synthetic_demo?'Synthetic showcase':'Imported observations';
    $('provenance').textContent=bundle.synthetic_demo?'Synthetic observations · A working inspection workflow, with no real farm or confirmed fault. The model was run in Python; these outputs are replayed here.':'Imported satellite-derived observations · Source IDs and geometry are supplied by the uploader and have not been independently verified. Historical review only; no field validation is claimed.';
    render();
  }
  function point(radius, degrees) {const a=(degrees-90)*Math.PI/180;return [250+radius*Math.cos(a),250+radius*Math.sin(a)];}
  function sectorPath(sector,ring) {const ri=ring*49,ro=(ring+1)*49,a=sector*30,b=a+30;const p=point(ro,a),q=point(ro,b),t=point(ri,b),u=point(ri,a);return ri===0?`M250 250 L${p} A${ro} ${ro} 0 0 1 ${q} Z`:`M${p} A${ro} ${ro} 0 0 1 ${q} L${t} A${ri} ${ri} 0 0 0 ${u} Z`;}
  function detail(z) {
    const box=$('detail'); box.replaceChildren(node('h3',z.zone_id+' / Evidence'));
    for (const text of [`Status: ${z.status} · NDVI ${z.ndvi.toFixed(3)}`,`${Math.round(z.radius_start_m)}–${Math.round(z.radius_end_m)} m from center · ${z.sector*30}–${z.sector*30+30}° clockwise from north`,`${Math.round(z.valid_coverage*100)}% valid coverage · ${z.observation_count} usable dates · ${z.persistence_count} recent candidate observations`,z.question]) box.append(node('p',text));
    if (z.source_id) box.append(node('p','Source: '+z.source_id));
    const h=bundle.observations.filter(o=>o.zone_id===z.zone_id&&String(o.date).slice(0,10)<=run.analysis_date).sort((a,b)=>String(a.date).localeCompare(String(b.date)));
    if (h.length>1) {const plot=svg('svg',{viewBox:'0 0 350 100',role:'img','aria-label':'Zone vegetation index history'});const pts=h.map((o,i)=>`${10+i*330/(h.length-1)},${90-(o.ndvi+1)*40}`).join(' ');plot.append(svg('path',{d:'M10 90 H340',fill:'none',stroke:'#ccd4c1'}),svg('polyline',{points:pts,fill:'none',stroke:'#315b42','stroke-width':2}));box.append(plot,node('p','NDVI history · dates through '+run.analysis_date,'fine'));}
  }
  function render() {
    run=bundle.runs[`${$('date').value}:${$('coverage').value}`];
    const tasks=run.zones.filter(z=>z.status==='inspect');
    $('task-count').textContent=tasks.length;$('zone-count').textContent=run.zones.length;
    $('coverage-stat').textContent=Math.round(run.zones.reduce((n,z)=>n+z.valid_coverage,0)/run.zones.length*100)+'%';
    $('dates-count').textContent=bundle.dates.filter(d=>d<=run.analysis_date).length;
    const map=$('pivot');map.replaceChildren();
    for (const z of run.zones) {const p=svg('path',{d:sectorPath(z.sector,z.ring),fill:colors[z.status],stroke:'#fafbf5','stroke-width':1.5,tabindex:0,role:'button','aria-label':`${z.zone_id}: ${z.status}, NDVI ${z.ndvi.toFixed(3)}`});const t=svg('title',{});t.textContent=`${z.zone_id} · ${z.status} · ${Math.round(z.valid_coverage*100)}% coverage`;p.append(t);p.addEventListener('click',()=>detail(z));p.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();detail(z);}});map.append(p);}
    for (const [text,x,y] of [['N',250,33],['E',471,255],['S',250,480],['W',29,255]]) {const t=svg('text',{x,y,'text-anchor':'middle',fill:'#647269','font-size':13,'font-family':'Arial'});t.textContent=text;map.append(t);}
    map.append(svg('circle',{cx:250,cy:250,r:5,fill:'#183e32'}));
    const queue=$('queue');queue.replaceChildren();
    if (!tasks.length) queue.append(node('p','No inspection candidate passed all gates for this date. Early dates establish the eight-date calibration history. Later dates need repeated candidate evidence.','empty'));
    const groups=new Map(); for(const t of tasks){if(!groups.has(t.sector))groups.set(t.sector,[]);groups.get(t.sector).push(t);}
    for (const [s,zones] of groups) {const el=node('article',undefined,'queue-item');el.append(node('strong',`Sector ${String(s+1).padStart(2,'0')} / ${s*30}–${s*30+30}°`),node('p',zones.map(z=>z.zone_id).join(', ')),node('p',zones[0].question));const b=node('button','Review evidence ↗');b.type='button';b.addEventListener('click',()=>detail(zones[0]));el.append(b);queue.append(el);}
    $('record-zone').replaceChildren(...run.zones.map(z=>option(z.zone_id,z.zone_id+' · '+z.status)));
    detail(tasks[0]||run.zones[0]);
    $('record-status').textContent=records.length?`${records.length} saved check(s) in this browser.`:'';
  }
  $('date').addEventListener('change',render);$('coverage').addEventListener('change',render);
  $('export').addEventListener('click',()=>download({...run,dataset_label:bundle.dataset_label,provenance:bundle.provenance},`${run.run_id}.json`));
  $('import').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>8*1024*1024)throw Error('Maximum bundle size is 8 MB.');const b=validate(JSON.parse(await f.text()));bundle=b;setup();$('message').textContent='Observation bundle imported. Review its source identifiers before use.';}catch(err){$('message').textContent='Import failed: '+err.message;}e.target.value='';});
  $('reset').addEventListener('click',()=>{bundle=window.RAIMAL_DATA;$('coverage').value='80';$('message').textContent='';setup();});
  $('inspection').addEventListener('submit',e=>{e.preventDefault();const record={run_id:run.run_id,dataset:bundle.dataset_label,synthetic:bundle.synthetic_demo,zone_id:$('record-zone').value,observation_date:run.analysis_date,finding:$('finding').value,measurement_and_follow_up:$('action').value.trim(),recorded_at:new Date().toISOString(),source:'User-entered finding; unverified'};records.push(record);try{localStorage.setItem('raimal-checks-v1',JSON.stringify(records));$('record-status').textContent='Saved in this browser. '+(record.synthetic?'This is a synthetic workflow record.':'This is a user-entered record, not independently verified.');}catch{$('record-status').textContent='Browser storage is unavailable. Export saved checks now to keep this record.';}$('action').value='';});
  $('export-records').addEventListener('click',()=>download(records,'raimal-field-checks.json'));
  $('pivots').addEventListener('input',e=>{const n=Number(e.target.value);$('pivots-value').textContent=n.toLocaleString('en');$('revenue').textContent='SAR '+(n*300).toLocaleString('en');});
  try{validate(bundle);setup();}catch(err){$('message').textContent='Unable to load dataset: '+err.message;}
})();
